### PR TITLE
add tags to generated language tests

### PR DESCRIPTION
**Pull request by berit**

### CODE REVIEW

**Review by plocket — APPROVED** [review]
Ran it, tooled around, looks good! We need to publish this as soon as we merge it.

**Comment by plocket** [comment]
I also didn't realize `npm run cucumber_base -- "$@" tests/features/*.feature` could run tests that don't have tags. Very thoughtful of the developers.

**Comment by plocket** [comment]
Rather, `npm run langs_setup && npm run cucumber -- $@`

**Review by plocket — COMMENTED** [review]
Hmm, also, does this need to change the action file that it pushes to other repos? (looking at the PR on MADE)
[The workflow file and the package.json, I think]

**Comment by plocket** [comment]
Will close #54, research tags

**Comment by plocket** [comment]
Will also address #19

**Comment by berit** [comment]
@plocket What does the comment about "isn't ignoring reports" mean? What reports?

**Comment by plocket** [comment]
We have files that get saved now that are called reports. They have `_report_` in the name. They give the tester some extra information about what happened during the tests.

I thought that we added `_report_` to the script that gives a repository its .gitignore, but something must have gotten lost along the way.

**Review by plocket — APPROVED** [review]
I think this is working correctly. See it being used with `extra_languages=Español` and `tags=@fast`: https://github.com/plocket/docassemble-MAEvictionDefense/runs/1676964971?check_suite_focus=true

**Pull request merged**
